//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.04 at 02:17:36 PM EEST 
//


package lt.viko.eif.ih.bakery.soap.model;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="bakery" type="{http://spring.io/guides/gs-producing-web-service}country"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bakery"
})
@XmlRootElement(name = "getBakeryByCustomerResponse")
public class GetBakeryByCustomerResponse {

    @XmlElement(required = true)
    protected Bakery bakery;

    /**
     * Gets the value of the bakery property.
     *
     * @return
     *     possible object is
     *     {@link Bakery }
     *
     */
    public Bakery getBakery() {
        return bakery;
    }

    /**
     * Sets the value of the bakery property.
     *
     * @param value
     *     allowed object is
     *     {@link Bakery }
     *
     */
    public void setBakery(Bakery value) {
        this.bakery = value;
    }

}
